### ISSUE TITLE
Lippmann data format

### ISSUE THREAD

**Issue by nevesanjos** [kbefus/pyres#2]
Thanks for developing this code. I am facing some problem with my Lippmann headers. Do you have any example using this kind of format?

My File does not have the statement "Electrode [" as your code expects.

Thank you in advance.

**Comment by kbefus** [comment]
Is there a different identifier for when the electrode information is loaded? I only had an example of a Lippmann data file from one colleague, so I assumed it was a standard format. If you can get your data into the same format as line 29 in the field example (use the example dataset to see what format the two outputs are in), then you should be good to go. You can splice in your own text reader function/routine and be on your way.
